# Generated by Django 5.0.6 on 2024-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('revenue', models.FloatField()),
                ('expenditure', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('performance', models.FloatField()),
                ('department', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('hrid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Email_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('Research_Papers', models.CharField(max_length=50)),
                ('conference', models.CharField(max_length=50)),
                ('funding', models.FloatField()),
            ],
        ),
    ]
