# Generated by Django 5.0.6 on 2024-05-20 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hrid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBSApp.hr'),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='empid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBSApp.employee'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='Email_address',
            field=models.EmailField(max_length=50),
        ),
    ]
