# Generated by Django 5.0.6 on 2024-05-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBSApp', '0002_employee_hrid_researchpaper_empid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='performance',
        ),
    ]
